name: xarray-tutorial
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy
  - cfgrib
  - cftime < 1.5
  - dask
  - dask-labextension
  - distributed
  - h5netcdf
  - hvplot
  - ipywidgets
  - jupyterlab-system-monitor
  - jupyterlab>=3
  - matplotlib
  - nc-time-axis
  - netcdf4
  - nodejs
  - pip
  - pre-commit
  - pydap
  - python-graphviz
  - python=3.9
  - scipy
  - watermark
  - xarray>=0.18.2
  - nbterm
